export enum Ideal {
    NO_IDEAL = "NO_IDEAL",
    FIRST_IDEAL = "NO_IDEAL",
    SECOND_IDEAL = "NO_IDEAL",
    THIRD_IDEAL = "NO_IDEAL",
    FOURTH_IDEAL = "NO_IDEAL",
    FIFTH_IDEAL = "NO_IDEAL"
}
