export enum Ideal {
    NO_IDEAL = 'NO_IDEAL',
    FIRST_IDEAL = 'FIRST_IDEAL',
    SECOND_IDEAL = 'SECOND_IDEAL',
    THIRD_IDEAL = 'THIRD_IDEAL',
    FOURTH_IDEAL = 'FOURTH_IDEAL',
    FIFTH_IDEAL = 'FIFTH_IDEAL'
}
